name: Run Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Install WebDriverManager (for browser drivers)
    - name: Install WebDriverManager
      run: |
        python -m webdriver_manager.chrome

    # Step 5: Run Robot Framework Tests
    - name: Run Robot Framework Tests
      run: |
        robot -d output tests/

    # Step 6: Upload Test Results
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: Robot-Test-Results
        path: output/
